---
title: "viz_and_eda_2"
author: "Hana Akbarnejad"
date: "10/1/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)

```

```{r load_data, cache = TRUE}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

weather_df

```

createscatterplot and adding labels:

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
  title = "Tempreture plot",
  x = "Minimun Temp (C)",
  y = "Maximum Temp (C)",
  caption = "Data from NOAA via rnoaa package"
  ) +
  scale_x_continuous(
    breaks = c(-15, -5, 20),
    labels = c("-15 c", "-5 c", "20 c")
  ) +
  scale_y_continuous(
    trans = "sqrt"
  )

```

COLORS!

```{r}

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
  title = "Tempreture plot",
  x = "Minimun Temp (C)",
  y = "Maximum Temp (C)",
  caption = "Data from NOAA via rnoaa package"
  ) +
  scale_color_hue(
    name = "Weatjer Station",
    h = c(50, 250)
  )
```

viridis package!

```{r}
ggp_base = 
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package"
  ) + 
  viridis::scale_color_viridis(
    name = "Location", 
    discrete = TRUE
  )

ggp_base

```


## THEMES!

where you write theme_minimal before theme!!!

```{r}
ggp_base +
  theme_minimal() +
  theme(legend.position = "bottom")

```

## more on dataset

```{r}

central_park = 
  weather_df %>% 
  filter(name == "CentralPark_NY")

waikiki = 
  weather_df %>% 
  filter(name == "Waikiki_HA")

ggplot(data = waikiki, aes(x = date, y = tmax, color = name)) + 
  geom_point() + 
  geom_line(data = central_park)

```

## multi-panel plot

```{r}
ggp_scatter =
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

```

```{r}

weather_df %>%
  mutate(name = factor(name),
  name = fct_relevel(name, c("Waikiki_HA", "CentralPark_NY", "Waterhole_WA"))) %>% 
  ggplot(aes(x = name, y = tmax)) + 
  geom_boxplot(aes(fill = name), color = "blue", alpha = .5) + 
  theme(legend.position = "bottom")
```

